module Bot
  module DiscordCommands
    module Race
      extend Discordrb::Commands::CommandContainer
      racebucket = bucket :bj, delay: 5
      command :race do |event, *args|
        bucketresponse = racebucket.rate_limited?(event.user)
         if bucketresponse
          event.send_temporary_message "**------------------------------**\n#{event.user.username} oynamak için #{bucketresponse.round(2)} saniye bekleyiniz.", 10.0
        else
        user = User.find_by(user_id: event.user.id)
        user = User.create(user_id: event.user.id) if user.nil?
        if args[1] == nil
          event.send_temporary_message "**------------------------------**\n#{nickrace} bet miktarını giriniz.(*race at bet)", 20.0
        elsif 0 <= args[1].to_i && args[1].to_i < 1000
          event.send_temporary_message "**------------------------------**\n#{nickrace} en düşük bet miktarı 1000", 20.0
        else
    if args[0].to_i == 1 || args[0].to_i == 2 || args[0].to_i == 3 || args[0].to_i == 4 || args[0].to_i == 5
          nickrace = event.user.username
          idrace = event.user.id
          if args[1].to_i > user.money
            event.send_temporary_message "**------------------------------**\n#{nickrace} yeterli paranız yok.Paranız: #{user.money}", 20.0
          else
            event.send "**------------------------------**"
	case args[0].to_i
	when 1
	  bet1 = nickrace
	when 2
	  bet2 = nickrace
	when 3
	  bet3 = nickrace
	when 4
	  bet4 = nickrace
	when 5
	  bet5 = nickrace
	end
          tekrarace = 1
          bet = args[1]
           user.money -= args[1].to_i
           user.save


a0 = ":horse_racing:"
a1 = ":heavy_minus_sign:"
a2 = ":heavy_minus_sign:"
a3 = ":heavy_minus_sign:"
a4 = ":heavy_minus_sign:"
a5 = ":heavy_minus_sign:"
a6 = ":heavy_minus_sign:"
a7 = ":heavy_minus_sign:"
a8 = ":heavy_minus_sign:"
a9 = ":heavy_minus_sign:"
a10 = ":heavy_minus_sign:"
a11 = ":heavy_minus_sign:"
a12 = ":heavy_minus_sign:"
a13 = ":heavy_minus_sign:"
a14 = ":heavy_minus_sign:"
a15 = ":heavy_minus_sign:"
awin = ":heavy_minus_sign:"
b0 = ":horse_racing:"
b1 = ":heavy_minus_sign:"
b2 = ":heavy_minus_sign:"
b3 = ":heavy_minus_sign:"
b4 = ":heavy_minus_sign:"
b5 = ":heavy_minus_sign:"
b6 = ":heavy_minus_sign:"
b7 = ":heavy_minus_sign:"
b8 = ":heavy_minus_sign:"
b9 = ":heavy_minus_sign:"
b10 = ":heavy_minus_sign:"
b11 = ":heavy_minus_sign:"
b12 = ":heavy_minus_sign:"
b13 = ":heavy_minus_sign:"
b14 = ":heavy_minus_sign:"
b15 = ":heavy_minus_sign:"
bwin = ":heavy_minus_sign:"
c0 = ":horse_racing:"
c1 = ":heavy_minus_sign:"
c2 = ":heavy_minus_sign:"
c3 = ":heavy_minus_sign:"
c4 = ":heavy_minus_sign:"
c5 = ":heavy_minus_sign:"
c6 = ":heavy_minus_sign:"
c7 = ":heavy_minus_sign:"
c8 = ":heavy_minus_sign:"
c9 = ":heavy_minus_sign:"
c10 = ":heavy_minus_sign:"
c11 = ":heavy_minus_sign:"
c12 = ":heavy_minus_sign:"
c13 = ":heavy_minus_sign:"
c14 = ":heavy_minus_sign:"
c15 = ":heavy_minus_sign:"
cwin = ":heavy_minus_sign:"
d0 = ":horse_racing:"
d1 = ":heavy_minus_sign:"
d2 = ":heavy_minus_sign:"
d3 = ":heavy_minus_sign:"
d4 = ":heavy_minus_sign:"
d5 = ":heavy_minus_sign:"
d6 = ":heavy_minus_sign:"
d7 = ":heavy_minus_sign:"
d8 = ":heavy_minus_sign:"
d9 = ":heavy_minus_sign:"
d10 = ":heavy_minus_sign:"
d11 = ":heavy_minus_sign:"
d12 = ":heavy_minus_sign:"
d13 = ":heavy_minus_sign:"
d14 = ":heavy_minus_sign:"
d15 = ":heavy_minus_sign:"
dwin = ":heavy_minus_sign:"
e0 = ":horse_racing:"
e1 = ":heavy_minus_sign:"
e2 = ":heavy_minus_sign:"
e3 = ":heavy_minus_sign:"
e4 = ":heavy_minus_sign:"
e5 = ":heavy_minus_sign:"
e6 = ":heavy_minus_sign:"
e7 = ":heavy_minus_sign:"
e8 = ":heavy_minus_sign:"
e9 = ":heavy_minus_sign:"
e10 = ":heavy_minus_sign:"
e11 = ":heavy_minus_sign:"
e12 = ":heavy_minus_sign:"
e13 = ":heavy_minus_sign:"
e14 = ":heavy_minus_sign:"
e15 = ":heavy_minus_sign:"
ewin = ":heavy_minus_sign:"

racemsg = event.send "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:	#{bet1}
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:	#{bet2}
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:	#{bet3}
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:	#{bet4}
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:	#{bet5}
"
akare = 0
bkare = 0
ckare = 0
dkare = 0
ekare = 0
oran = 0
loop do
  break if akare > 15
  break if bkare > 15
  break if ckare > 15
  break if dkare > 15
  break if ekare > 15
  ilerleme = [2,3,4,5,6]
arand = ilerleme.sample
ilerleme.delete(arand)
brand = ilerleme.sample
ilerleme.delete(brand)
crand = ilerleme.sample
ilerleme.delete(crand)
drand = ilerleme.sample
ilerleme.delete(drand)
erand = ilerleme.sample
ilerleme.delete(erand)

akare += arand
bkare += brand
ckare += crand
dkare += drand
ekare += erand

case akare
when 2
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":horse_racing:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 3
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":horse_racing:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 4
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":horse_racing:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 5
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":horse_racing:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 6
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":horse_racing:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 7
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":horse_racing:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 8
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":horse_racing:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 9
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":horse_racing:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 10
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":horse_racing:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 11
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":horse_racing:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 12
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":horse_racing:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 13
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":horse_racing:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
when 14
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":horse_racing:"
  a15 = ":heavy_minus_sign:"
when 15
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":horse_racing:"
else
  if akare >= bkare && akare >= ckare && akare >= dkare && akare >= ekare
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":heavy_minus_sign:"
  awin = ":horse_racing:"
  oran += 1
else
  a0 = ":heavy_minus_sign:"
  a1 = ":heavy_minus_sign:"
  a2 = ":heavy_minus_sign:"
  a3 = ":heavy_minus_sign:"
  a4 = ":heavy_minus_sign:"
  a5 = ":heavy_minus_sign:"
  a6 = ":heavy_minus_sign:"
  a7 = ":heavy_minus_sign:"
  a8 = ":heavy_minus_sign:"
  a9 = ":heavy_minus_sign:"
  a10 = ":heavy_minus_sign:"
  a11 = ":heavy_minus_sign:"
  a12 = ":heavy_minus_sign:"
  a13 = ":heavy_minus_sign:"
  a14 = ":heavy_minus_sign:"
  a15 = ":horse_racing:"
end
end

case bkare
when 2
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":horse_racing:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 3
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":horse_racing:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 4
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":horse_racing:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 5
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":horse_racing:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 6
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":horse_racing:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 7
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":horse_racing:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 8
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":horse_racing:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 9
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":horse_racing:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 10
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":horse_racing:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 11
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":horse_racing:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 12
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":horse_racing:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 13
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":horse_racing:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
when 14
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":horse_racing:"
  b15 = ":heavy_minus_sign:"
when 15
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":horse_racing:"
else
  if bkare >= akare && bkare >= ckare && bkare >= dkare && bkare >= ekare
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":heavy_minus_sign:"
  bwin = ":horse_racing:"
  oran += 1
else
  b0 = ":heavy_minus_sign:"
  b1 = ":heavy_minus_sign:"
  b2 = ":heavy_minus_sign:"
  b3 = ":heavy_minus_sign:"
  b4 = ":heavy_minus_sign:"
  b5 = ":heavy_minus_sign:"
  b6 = ":heavy_minus_sign:"
  b7 = ":heavy_minus_sign:"
  b8 = ":heavy_minus_sign:"
  b9 = ":heavy_minus_sign:"
  b10 = ":heavy_minus_sign:"
  b11 = ":heavy_minus_sign:"
  b12 = ":heavy_minus_sign:"
  b13 = ":heavy_minus_sign:"
  b14 = ":heavy_minus_sign:"
  b15 = ":horse_racing:"
end
end

case ckare
when 2
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":horse_racing:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 3
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":horse_racing:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 4
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":horse_racing:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 5
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":horse_racing:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 6
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":horse_racing:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 7
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":horse_racing:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 8
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":horse_racing:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 9
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":horse_racing:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 10
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":horse_racing:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 11
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":horse_racing:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 12
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":horse_racing:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 13
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":horse_racing:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
when 14
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":horse_racing:"
  c15 = ":heavy_minus_sign:"
when 15
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":horse_racing:"
else
  if ckare >= akare && ckare >= bkare && ckare >= dkare && ckare >= ekare
  c0 = ":heavy_minus_sign:"
  c1 = ":heavy_minus_sign:"
  c2 = ":heavy_minus_sign:"
  c3 = ":heavy_minus_sign:"
  c4 = ":heavy_minus_sign:"
  c5 = ":heavy_minus_sign:"
  c6 = ":heavy_minus_sign:"
  c7 = ":heavy_minus_sign:"
  c8 = ":heavy_minus_sign:"
  c9 = ":heavy_minus_sign:"
  c10 = ":heavy_minus_sign:"
  c11 = ":heavy_minus_sign:"
  c12 = ":heavy_minus_sign:"
  c13 = ":heavy_minus_sign:"
  c14 = ":heavy_minus_sign:"
  c15 = ":heavy_minus_sign:"
  cwin = ":horse_racing:"
  oran += 1
else
c0 = ":heavy_minus_sign:"
c1 = ":heavy_minus_sign:"
c2 = ":heavy_minus_sign:"
c3 = ":heavy_minus_sign:"
c4 = ":heavy_minus_sign:"
c5 = ":heavy_minus_sign:"
c6 = ":heavy_minus_sign:"
c7 = ":heavy_minus_sign:"
c8 = ":heavy_minus_sign:"
c9 = ":heavy_minus_sign:"
c10 = ":heavy_minus_sign:"
c11 = ":heavy_minus_sign:"
c12 = ":heavy_minus_sign:"
c13 = ":heavy_minus_sign:"
c14 = ":heavy_minus_sign:"
c15 = ":horse_racing:"
end
end

case dkare
when 2
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":horse_racing:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 3
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":horse_racing:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 4
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":horse_racing:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 5
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":horse_racing:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 6
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":horse_racing:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 7
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":horse_racing:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 8
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":horse_racing:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 9
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":horse_racing:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 10
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":horse_racing:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 11
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":horse_racing:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 12
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":horse_racing:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 13
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":horse_racing:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
when 14
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":horse_racing:"
  d15 = ":heavy_minus_sign:"
when 15
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":horse_racing:"
else
  if dkare >= akare && dkare >= bkare && dkare >= ckare && dkare >= ekare
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":heavy_minus_sign:"
  dwin = ":horse_racing:"
  oran += 1
else
  d0 = ":heavy_minus_sign:"
  d1 = ":heavy_minus_sign:"
  d2 = ":heavy_minus_sign:"
  d3 = ":heavy_minus_sign:"
  d4 = ":heavy_minus_sign:"
  d5 = ":heavy_minus_sign:"
  d6 = ":heavy_minus_sign:"
  d7 = ":heavy_minus_sign:"
  d8 = ":heavy_minus_sign:"
  d9 = ":heavy_minus_sign:"
  d10 = ":heavy_minus_sign:"
  d11 = ":heavy_minus_sign:"
  d12 = ":heavy_minus_sign:"
  d13 = ":heavy_minus_sign:"
  d14 = ":heavy_minus_sign:"
  d15 = ":horse_racing:"
end
end


case ekare
when 2
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":horse_racing:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 3
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":horse_racing:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 4
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":horse_racing:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 5
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":horse_racing:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 6
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":horse_racing:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 7
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":horse_racing:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 8
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":horse_racing:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 9
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":horse_racing:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 10
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":horse_racing:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 11
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":horse_racing:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 12
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":horse_racing:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 13
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":horse_racing:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
when 14
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":horse_racing:"
  e15 = ":heavy_minus_sign:"
when 15
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":horse_racing:"
else
  if ekare >= akare && ekare >= bkare && ekare >= ckare && ekare >= dkare
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":heavy_minus_sign:"
  ewin = ":horse_racing:"
  oran += 1
else
  e0 = ":heavy_minus_sign:"
  e1 = ":heavy_minus_sign:"
  e2 = ":heavy_minus_sign:"
  e3 = ":heavy_minus_sign:"
  e4 = ":heavy_minus_sign:"
  e5 = ":heavy_minus_sign:"
  e6 = ":heavy_minus_sign:"
  e7 = ":heavy_minus_sign:"
  e8 = ":heavy_minus_sign:"
  e9 = ":heavy_minus_sign:"
  e10 = ":heavy_minus_sign:"
  e11 = ":heavy_minus_sign:"
  e12 = ":heavy_minus_sign:"
  e13 = ":heavy_minus_sign:"
  e14 = ":heavy_minus_sign:"
  e15 = ":horse_racing:"
end
end
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:	#{bet1}
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:	#{bet2}
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:	#{bet3}
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:	#{bet4}
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:	#{bet5}
"
sleep(1)
end
            case args[0]
            when "1"
              if awin == ":horse_racing:"
                user.money += (args[1].to_i * (5.0/oran)).ceil
                user.save
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:	#{nickrace} kazandınız.Paranız: #{user.money}
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
              else
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:	#{nickrace} kaybettiniz.Paranız: #{user.money}
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
                end
            when "2"
              if bwin == ":horse_racing:"
                  user.money += (args[1].to_i * (5.0/oran)).ceil
                  user.save
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:	#{nickrace} kazandınız.Paranız: #{user.money}
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
              else
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:	#{nickrace} kaybettiniz.Paranız: #{user.money}
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
                end

            when "3"
              if cwin == ":horse_racing:"
                user.money += (args[1].to_i * (5.0/oran)).ceil
                user.save
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:  #{nickrace} kazandınız.Paranız: #{user.money}
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
              else
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:  #{nickrace} kaybettiniz.Paranız: #{user.money}
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
                end
            when "4"
              if dwin == ":horse_racing:"
                user.money += (args[1].to_i * (5.0/oran)).ceil
                user.save
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:	#{nickrace} kazandınız.Paranız: #{user.money}
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
              else
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:	#{nickrace} kaybettiniz.Paranız: #{user.money}
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:
"
                nil
                end
              when "5"
                if ewin == ":horse_racing:"
                  user.money += (args[1].to_i * (5.0/oran)).ceil
                  user.save
racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:	#{nickrace} kazandınız.Paranız: #{user.money}
"
                  nil
                else
  racemsg.edit "
#{awin}:checkered_flag:#{a15}#{a14}#{a13}#{a12}#{a11}#{a10}#{a9}#{a8}#{a7}#{a6}#{a5}#{a4}#{a3}#{a2}#{a1}:checkered_flag:#{a0}:one:
#{bwin}:checkered_flag:#{b15}#{b14}#{b13}#{b12}#{b11}#{b10}#{b9}#{b8}#{b7}#{b6}#{b5}#{b4}#{b3}#{b2}#{b1}:checkered_flag:#{b0}:two:
#{cwin}:checkered_flag:#{c15}#{c14}#{c13}#{c12}#{c11}#{c10}#{c9}#{c8}#{c7}#{c6}#{c5}#{c4}#{c3}#{c2}#{c1}:checkered_flag:#{c0}:three:
#{dwin}:checkered_flag:#{d15}#{d14}#{d13}#{d12}#{d11}#{d10}#{d9}#{d8}#{d7}#{d6}#{d5}#{d4}#{d3}#{d2}#{d1}:checkered_flag:#{d0}:four:
#{ewin}:checkered_flag:#{e15}#{e14}#{e13}#{e12}#{e11}#{e10}#{e9}#{e8}#{e7}#{e6}#{e5}#{e4}#{e3}#{e2}#{e1}:checkered_flag:#{e0}:five:	#{nickrace} kaybettiniz.Paranız: #{user.money}
"
                  nil
                  end
            end
          end

else
  event.send_temporary_message "**------------------------------**\n#{nickrace} *race at bet komutunu kullanınız.(*race 1 10)", 20.0
end
end
end
  event.message.delete
      end
    end
  end
end
